<?php

use Illuminate\Database\Seeder;

class MinhchungctdtTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         DB::table('minhchungctdts')->insert([
        	['tenminhchung'=>'Mục tiêu và chuẩn đầu ra của chương trình đào tạo.', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2020-10-29 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-1-01-01','tentieuchuan' => 'Tiêu chuẩn 1', 'tentieuchi'=> 'Tiêu chí 1.1', 'tencap' => 'CTDT', 'noidung' => 'Kết quả học tập mong đợi được xây dựng rõ ràng, tương thích với tầm nhìn và sứ mạng của nhà trường.','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
        	['tenminhchung'=>'Mục tiêu và chuẩn đầu ra của chương trình đào tạo.', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2020-10-29 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-1-02-01','tentieuchuan' => 'Tiêu chuẩn 1', 'tentieuchi'=> 'Tiêu chí 1.2', 'tencap' => 'CTDT', 'noidung' => 'Kết quả học tập mong đợi bao gồm cả đầu ra chuyên ngành và đầu ra tổng quát (kỹ năng mềm).','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
        	['tenminhchung'=>'Mục tiêu và chuẩn đầu ra của chương trình đào tạo.', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2020-10-29 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-1-03-01','tentieuchuan' => 'Tiêu chuẩn 1', 'tentieuchi'=> 'Tiêu chí 1.3', 'tencap' => 'CTDT', 'noidung' => 'Kết quả học tập mong đợi phản ánh rõ ràng yêu cầu của các bên liên quan','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
        
            ['tenminhchung'=>'Hoạt động dạy và học', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-2-01-01','tentieuchuan' => 'Tiêu chuẩn 2', 'tentieuchi'=> 'Tiêu chí 2.1', 'tencap' => 'CTDT', 'noidung' => 'CTĐT được thiết kế dựa trên nguyên tắc đảm bảo “tương thích có định hướng” với kết quả học tập mong đợi','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
            ['tenminhchung'=>'Hoạt động dạy và học', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-2-02-01','tentieuchuan' => 'Tiêu chuẩn 2', 'tentieuchi'=> 'Tiêu chí 2.2', 'tencap' => 'CTDT', 'noidung' => 'Mức độ đóng góp của mỗi môn học vào việc đạt được kết quả học tập mong đợi được xác định rõ ràng','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
        	['tenminhchung'=>'Hoạt động dạy và học', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-2-03-01','tentieuchuan' => 'Tiêu chuẩn 2', 'tentieuchi'=> 'Tiêu chí 2.3', 'tencap' => 'CTDT', 'noidung' => 'CTĐT được xây dựng với cấu trúc và trình tự hợp lý, có sự gắn kết giữa các môn học và mang tính cập nhật','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
            
            ['tenminhchung'=>'Hoạt động kiểm tra, đánh giá kết quả học tập của người học', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-3-01-01','tentieuchuan' => 'Tiêu chuẩn 3', 'tentieuchi'=> 'Tiêu chí 3.1', 'tencap' => 'CTDT', 'noidung' => 'CTĐT được thiết kế dựa trên nguyên tắc đảm bảo “tương thích có định hướng” với kết quả học tập mong đợi','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
        	['tenminhchung'=>'Hoạt động kiểm tra, đánh giá kết quả học tập của người học', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-3-02-01','tentieuchuan' => 'Tiêu chuẩn 3', 'tentieuchi'=> 'Tiêu chí 3.2', 'tencap' => 'CTDT', 'noidung' => 'Mức độ đóng góp của mỗi môn học vào việc đạt được kết quả học tập mong đợi được xác định rõ ràng','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
            ['tenminhchung'=>'Hoạt động kiểm tra, đánh giá kết quả học tập của người học', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-3-03-01','tentieuchuan' => 'Tiêu chuẩn 3', 'tentieuchi'=> 'Tiêu chí 3.3', 'tencap' => 'CTDT', 'noidung' => 'CTĐT được xây dựng với cấu trúc và trình tự hợp lý, có sự gắn kết giữa các môn học và mang tính cập nhật','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],

            ['tenminhchung'=>'Hoạt động kiểm tra, đánh giá kết quả học tập của người học', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-4-01-01','tentieuchuan' => 'Tiêu chuẩn 4', 'tentieuchi'=> 'Tiêu chí 4.1', 'tencap' => 'CTDT', 'noidung' => 'Triết lý giáo dục được trình bày rõ ràng và phổ biến đến tất cả các bên liên quan','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
        	['tenminhchung'=>'Hoạt động kiểm tra, đánh giá kết quả học tập của người học', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-4-02-01','tentieuchuan' => 'Tiêu chuẩn 4', 'tentieuchi'=> 'Tiêu chí 4.2', 'tencap' => 'CTDT', 'noidung' => 'Hoạt động dạy và học được xây dựng theo nguyên tắc “tương thích có định hướng” nhằm đảm bảo việc đạt được kết quả học tập mong đợi','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
            ['tenminhchung'=>'Hoạt động kiểm tra, đánh giá kết quả học tập của người học', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-4-03-01','tentieuchuan' => 'Tiêu chuẩn 4', 'tentieuchi'=> 'Tiêu chí 4.3', 'tencap' => 'CTDT', 'noidung' => 'Hoạt động dạy và học thúc đẩy học tập suốt đời','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
            
            ['tenminhchung'=>'Đội ngũ giảng viên, nghiên cứu viên', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-5-01-01','tentieuchuan' => 'Tiêu chuẩn 5', 'tentieuchi'=> 'Tiêu chí 5.1', 'tencap' => 'CTDT', 'noidung' => 'Hoạt động kiểm tra đánh giá SV tương thích với các kết quả học tập mong đợi','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
        	['tenminhchung'=>'Đội ngũ giảng viên, nghiên cứu viên', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-5-02-01','tentieuchuan' => 'Tiêu chuẩn 5', 'tentieuchi'=> 'Tiêu chí 5.2', 'tencap' => 'CTDT', 'noidung' => 'Thông tin về hoạt động kiểm tra, đánh giá được thông báo công khai và phổ biến đến SV, bao gồm: các mốc thời gian; các phương pháp kiểm tra, đánh giá; tỉ lệ phân bổ điểm; bảng tiêu chí đánh giá và thang điểm','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
        	['tenminhchung'=>'Đội ngũ giảng viên, nghiên cứu viên', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-5-03-01','tentieuchuan' => 'Tiêu chuẩn 5', 'tentieuchi'=> 'Tiêu chí 5.3', 'tencap' => 'CTDT', 'noidung' => 'Các phương pháp kiểm tra, đánh giá bao gồm bảng tiêu chí đánh giá và thang điểm, được sử dụng để đảm bảo hoạt động kiểm tra đánh giá có độ giá trị, độ tin cậy và sự công bằng','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
        	['tenminhchung'=>'Đội ngũ giảng viên, nghiên cứu viên', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-5-04-01','tentieuchuan' => 'Tiêu chuẩn 5', 'tentieuchi'=> 'Tiêu chí 5.4', 'tencap' => 'CTDT', 'noidung' => 'Thông tin phản hồi kết quả kiểm tra, đánh giá được gửi kịp thời và giúp cải thiện chất lượng học tập','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],   
            ['tenminhchung'=>'Đội ngũ giảng viên, nghiên cứu viên', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-5-05-01','tentieuchuan' => 'Tiêu chuẩn 5', 'tentieuchi'=> 'Tiêu chí 5.5', 'tencap' => 'CTDT', 'noidung' => 'Có quy trình khiếu nại về kết quả kiểm tra, đánh giá hợp lý để SV dễ dàng tiếp cận','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
            
            ['tenminhchung'=>'Đội ngũ nhân viên', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-6-01-01','tentieuchuan' => 'Tiêu chuẩn 6', 'tentieuchi'=> 'Tiêu chí 6.1', 'tencap' => 'CTDT', 'noidung' => 'Có triển khai kế hoạch phát triển đội ngũ GV (đội ngũ kế thừa, thăng chức, nâng bậc, tái phân công nhiệm vụ, chấm dứt hợp đồng, hưu trí) để đáp ứng nhu cầu đào tạo, nghiên cứu và phục vụ cộng đồng','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
        	['tenminhchung'=>'Đội ngũ nhân viên', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-6-02-01','tentieuchuan' => 'Tiêu chuẩn 6', 'tentieuchi'=> 'Tiêu chí 6.2', 'tencap' => 'CTDT', 'noidung' => 'Tỉ lệ GV/SV và tải trọng công việc được đo lường và giám sát để cải tiến chất lượng giảng dạy, nghiên cứu và phục vụ cộng đồng','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
        	['tenminhchung'=>'Đội ngũ nhân viên', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-6-03-01','tentieuchuan' => 'Tiêu chuẩn 6', 'tentieuchi'=> 'Tiêu chí 6.3', 'tencap' => 'CTDT', 'noidung' => 'Các tiêu chí tuyển dụng và tiêu chí tuyển chọn để bổ nhiệm, phân công và nâng bậc, bao gồm cả tiêu chuẩn về đạo đức và tự do học thuật được xác định rõ và phổ biến đến các bên liên quan','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
        	['tenminhchung'=>'Đội ngũ nhân viên', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-6-04-01','tentieuchuan' => 'Tiêu chuẩn 6', 'tentieuchi'=> 'Tiêu chí 6.4', 'tencap' => 'CTDT', 'noidung' => 'Năng lực của GV được xác định rõ và được đánh giá','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
        	['tenminhchung'=>'Đội ngũ nhân viên', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-6-05-01','tentieuchuan' => 'Tiêu chuẩn 6', 'tentieuchi'=> 'Tiêu chí 6.5', 'tencap' => 'CTDT', 'noidung' => 'Nhu cầu về đào tạo, phát triển chuyên môn cho GV được xác định và có triển khai các hoạt động phù hợp để đáp ứng những nhu cầu này','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
        	['tenminhchung'=>'Đội ngũ nhân viên', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-6-06-01','tentieuchuan' => 'Tiêu chuẩn 6', 'tentieuchi'=> 'Tiêu chí 6.6', 'tencap' => 'CTDT', 'noidung' => 'Việc quản lý theo kết quả công việc của giảng viên (gồm cả khen thưởng và công nhận) được triển khai để khuyến khích và hỗ trợ cho đào tạo, nghiên cứu khoa học và các hoạt động phục vụ cộng đồng','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],  
            ['tenminhchung'=>'Đội ngũ nhân viên', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-6-07-01','tentieuchuan' => 'Tiêu chuẩn 6', 'tentieuchi'=> 'Tiêu chí 6.7', 'tencap' => 'CTDT', 'noidung' => 'Các loại hình và số lượng các hoạt động nghiên cứu của GV được quy định rõ, giám sát và đối sánh để cải tiến chất lượng','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
            
            ['tenminhchung'=>'Cơ sở hạ tầng công nghệ', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-7-01-01','tentieuchuan' => 'Tiêu chuẩn 7', 'tentieuchi'=> 'Tiêu chí 7.1', 'tencap' => 'CTDT', 'noidung' => 'Công tác quy hoạch đội ngũ cán bộ hỗ trợ (làm việc tại thư viện, phòng thực hành, mảng công nghệ thông tin và các đơn vị hỗ trợ SV khác) được triển khai, đáp ứng nhu cầu đào tạo, nghiên cứu và phục vụ cộng đồng','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
        	['tenminhchung'=>'Cơ sở hạ tầng công nghệ', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-7-02-01','tentieuchuan' => 'Tiêu chuẩn 7', 'tentieuchi'=> 'Tiêu chí 7.2', 'tencap' => 'CTDT', 'noidung' => 'Tiêu chí tuyển dụng, bổ nhiệm và nâng bậc được xác định rõ và phổ biến rộng rãi','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
        	['tenminhchung'=>'Cơ sở hạ tầng công nghệ', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-7-03-01','tentieuchuan' => 'Tiêu chuẩn 7', 'tentieuchi'=> 'Tiêu chí 7.3', 'tencap' => 'CTDT', 'noidung' => 'Năng lực của cán bộ hỗ trợ được xác định rõ và đánh giá','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
        	['tenminhchung'=>'Cơ sở hạ tầng công nghệ', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-7-04-01','tentieuchuan' => 'Tiêu chuẩn 7', 'tentieuchi'=> 'Tiêu chí 7.4', 'tencap' => 'CTDT', 'noidung' => 'Nhu cầu đào tạo và phát triển chuyên môn, nghiệp vụ cho đội ngũ cán bộ hỗ trợ được xác định và có các hoạt động được triển khai đáp ứng các nhu cầu này','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
        	['tenminhchung'=>'Cơ sở hạ tầng công nghệ', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-7-05-01','tentieuchuan' => 'Tiêu chuẩn 7', 'tentieuchi'=> 'Tiêu chí 7.5', 'tencap' => 'CTDT', 'noidung' => 'Việc quản lý theo hiệu quả công việc bao gồm khen thưởng và công nhận được thực hiện để thúc đẩy và hỗ trợ cho hoạt động đào tạo, nghiên cứu và phục vụ cộng đồng','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
            
            ['tenminhchung'=>'Quản lý triển khai chương trình đào tạo', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-8-01-01','tentieuchuan' => 'Tiêu chuẩn 8', 'tentieuchi'=> 'Tiêu chí 8.1', 'tencap' => 'CTDT', 'noidung' => 'Chính sách và tiêu chí tuyển sinh được xác định rõ ràng, được ban hành, phổ biến và cập nhật','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
            ['tenminhchung'=>'Quản lý triển khai chương trình đào tạo', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-8-02-01','tentieuchuan' => 'Tiêu chuẩn 8', 'tentieuchi'=> 'Tiêu chí 8.1', 'tencap' => 'CTDT', 'noidung' => 'Các phương pháp và tiêu chí tuyển sinh được xác định rõ và được đánh giá','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
        	['tenminhchung'=>'Quản lý triển khai chương trình đào tạo', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-8-03-01','tentieuchuan' => 'Tiêu chuẩn 8', 'tentieuchi'=> 'Tiêu chí 8.2', 'tencap' => 'CTDT', 'noidung' => 'Có hệ thống phù hợp để giám sát tiến độ học tập, kết quả học và tải trọng học tập của SV','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
        	['tenminhchung'=>'Quản lý triển khai chương trình đào tạo', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-8-04-01','tentieuchuan' => 'Tiêu chuẩn 8', 'tentieuchi'=> 'Tiêu chí 8.3', 'tencap' => 'CTDT', 'noidung' => 'Có các hoạt động tư vấn học tập, các hoạt động ngoại khóa, thi đua và những dịch vụ hỗ trợ khác dành cho SV giúp nâng cao chất lượng học tập và khả năng tìm được việc làm của SV','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
        	['tenminhchung'=>'Quản lý triển khai chương trình đào tạo', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-8-05-01','tentieuchuan' => 'Tiêu chuẩn 8', 'tentieuchi'=> 'Tiêu chí 8.4', 'tencap' => 'CTDT', 'noidung' => 'Môi trường tâm lý, xã hội và cảnh quan hỗ trợ hiệu quả cho hoạt động đào tạo và nghiên cứu cũng như tạo sự thoải mái cho SV','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
            
            ['tenminhchung'=>'Cơ sở hạ tầng và trang thiết bị', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-9-01-01','tentieuchuan' => 'Tiêu chuẩn 9', 'tentieuchi'=> 'Tiêu chí 9.1', 'tencap' => 'CTDT', 'noidung' => 'Cơ sở vật chất và trang thiết bị phục vụ dạy và học (như giảng đường, phòng học, phòng chuyên đề,…) được trang bị đủ và cập nhật để hỗ trợ hoạt động đào tạo và nghiên cứu','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
            ['tenminhchung'=>'Cơ sở hạ tầng và trang thiết bị', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-9-02-01','tentieuchuan' => 'Tiêu chuẩn 9', 'tentieuchi'=> 'Tiêu chí 9.2', 'tencap' => 'CTDT', 'noidung' => 'Thư viện và các nguồn học liệu được trang bị đầy đủ và cập nhật để hỗ trợ hoạt động đào tạo và nghiên cứu','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
        	['tenminhchung'=>'Cơ sở hạ tầng và trang thiết bị', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-9-03-01','tentieuchuan' => 'Tiêu chuẩn 9', 'tentieuchi'=> 'Tiêu chí 9.3', 'tencap' => 'CTDT', 'noidung' => 'Các phòng thí nghiệm và trang thiết bị được trang bị đầy đủ và cập nhật để hỗ trợ hoạt động đào tạo và nghiên cứu','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
        	['tenminhchung'=>'Cơ sở hạ tầng và trang thiết bị', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-9-04-01','tentieuchuan' => 'Tiêu chuẩn 9', 'tentieuchi'=> 'Tiêu chí 9.4', 'tencap' => 'CTDT', 'noidung' => 'Hệ thống công nghệ thông tin (bao gồm cả hạ tầng phục vụ học trực truyến) được trang bị đầy đủ và cập nhật để hỗ trợ hoạt động đào tạo và nghiên cứu','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
            ['tenminhchung'=>'Cơ sở hạ tầng và trang thiết bị', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-9-05-01','tentieuchuan' => 'Tiêu chuẩn 9', 'tentieuchi'=> 'Tiêu chí 9.5', 'tencap' => 'CTDT', 'noidung' => 'Các tiêu chuẩn về môi trường, sức khỏe và an toàn được xác định và thực hiện; có lưu ý đến nhu cầu đặc thù của người khuyết tật','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
            
            ['tenminhchung'=>'Nâng cao chất lượng', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-10-01-01','tentieuchuan' => 'Tiêu chuẩn 10', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'tentieuchi'=> 'Tiêu chí 10.1', 'tencap' => 'CTDT', 'noidung' => 'Nhu cầu và thông tin phản hồi của các bên liên quan được sử dụng để phục vụ cho hoạt động thiết kế và phát triển CTĐT','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
        	['tenminhchung'=>'Nâng cao chất lượng', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-10-02-01','tentieuchuan' => 'Tiêu chuẩn 10', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'tentieuchi'=> 'Tiêu chí 10.2', 'tencap' => 'CTDT', 'noidung' => 'Quy trình thiết kế và phát triển CTĐT được xây dựng, đánh giá và cải tiến chất lượng','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
        	['tenminhchung'=>'Nâng cao chất lượng', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-10-03-01','tentieuchuan' => 'Tiêu chuẩn 10', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'tentieuchi'=> 'Tiêu chí 10.3', 'tencap' => 'CTDT', 'noidung' => 'Quá trình dạy và học, hoạt động kiểm tra đánh giá SV được thường xuyên rà soát, đánh giá để đảm bảo sự phù hợp và tương thích','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
        	['tenminhchung'=>'Nâng cao chất lượng', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-10-04-01','tentieuchuan' => 'Tiêu chuẩn 10', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'tentieuchi'=> 'Tiêu chí 10.4', 'tencap' => 'CTDT', 'noidung' => 'Chất lượng các dịch vụ hỗ trợ và trang thiết bị (tại thư viện, phòng thí nghiệm, hệ thống công nghệ thông tin và các dịch vụ hỗ trợ SV) được đánh giá và cải tiến chất lượng [Các thành quả nghiên cứu được sử dụng để nâng cao chất lượng hoạt động dạy và học','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
        	['tenminhchung'=>'Nâng cao chất lượng', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-10-05-01','tentieuchuan' => 'Tiêu chuẩn 10', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'tentieuchi'=> 'Tiêu chí 10.5', 'tencap' => 'CTDT', 'noidung' => 'Chất lượng các dịch vụ hỗ trợ và trang thiết bị (tại thư viện, phòng thí nghiệm, hệ thống công nghệ thông tin và các dịch vụ hỗ trợ SV) được đánh giá và cải tiến chất lượng','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
        	['tenminhchung'=>'Nâng cao chất lượng', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-10-06-01','tentieuchuan' => 'Tiêu chuẩn 10', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'tentieuchi'=> 'Tiêu chí 10.6', 'tencap' => 'CTDT', 'noidung' => 'Cơ chế thu thập ý kiến phản hồi và góp ý từ cán bộ, GV, SV, cựu SV và nhà tuyển dụng có tính hệ thống và được đánh giá, cải tiến chất lượng','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
           
            ['tenminhchung'=>'Đầu ra', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-11-01-01','tentieuchuan' => 'Tiêu chuẩn 11', 'tentieuchi'=> 'Tiêu chí 11.1', 'tencap' => 'CTDT', 'noidung' => 'Tỷ lệ thôi học và tỷ lệ tốt nghiệp được xác định, giám sát và đối sánh để cải tiến chất lượng','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
        	['tenminhchung'=>'Đầu ra', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-11-02-01','tentieuchuan' => 'Tiêu chuẩn 11', 'tentieuchi'=> 'Tiêu chí 11.2', 'tencap' => 'CTDT', 'noidung' => 'Thời gian tốt nghiệp trung bình được xác định, giám sát và đối sánh để cải tiến chất lượng','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
        	['tenminhchung'=>'Đầu ra', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-11-03-01','tentieuchuan' => 'Tiêu chuẩn 11', 'tentieuchi'=> 'Tiêu chí 11.3', 'tencap' => 'CTDT', 'noidung' => 'Tỷ lệ có việc làm của SV sau khi tốt nghiệp được xác định, giám sát và đối sánh để cải tiến chất lượng','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
        	['tenminhchung'=>'Đầu ra', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-11-04-01','tentieuchuan' => 'Tiêu chuẩn 11', 'tentieuchi'=> 'Tiêu chí 11.4', 'tencap' => 'CTDT', 'noidung' => 'Loại hình và số lượng các hoạt động nghiên cứu khoa học của SV được quy định rõ, giám sát và đối sánh để cải tiến chất lượng','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
        	['tenminhchung'=>'Đầu ra', 'noibanhanh'=>'BGĐT', 'ngaybanhanh' => '2019-12-10 00:00:00', 'tenctdt' => "Khoa Toán-Cơ-Tin học", 'sohieu' => 'H2-11-05-01','tentieuchuan' => 'Tiêu chuẩn 11', 'tentieuchi'=> 'Tiêu chí 11.5', 'tencap' => 'CTDT', 'noidung' => 'Mức độ hài lòng của các bên liên quan được xác định, giám sát và đối sánh để cải tiến chất lượng','file' => 'danh-muc-ma-minh-chung-danh-gia.doc'],
        	
        
        
        
        ]);
    }
}
