<?php

use Illuminate\Database\Seeder;

class TieuchictdtTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('tieuchictdts')->insert([
        	['tentieuchi'=>'Tiêu chí 1.1','tentieuchuan'=>'Tiêu chuẩn 1','tencap'=>'CTDT','noidung'=>'Mục tiêu của chương trình đào tạo được xác định rõ ràng, phù hợp với sứ mạng và tầm nhìn của cơ sở giáo dục đại học, phù hợp với Mục tiêu của giáo dục đại học quy định tại Luật giáo dục đại học.'],
        	['tentieuchi'=>'Tiêu chí 1.2','tentieuchuan'=>'Tiêu chuẩn 1','tencap'=>'CTDT','noidung'=>'Chuẩn đầu ra của chương trình đào tạo được xác định rõ ràng theo quy định tại Khung trình độ quốc gia Việt Nam, bao quát được cả yêu cầu chung và yêu cầu chuyên biệt, phản ánh được yêu cầu của các bên liên quan; bảo đảm tương tự như chuẩn đầu ra của chương trình đào tạo chính quy cùng ngành; được định kỳ rà soát, điều chỉnh và được công bố công khai.'],
        	['tentieuchi'=>'Tiêu chí 2.1','tentieuchuan'=>'Tiêu chuẩn 2','tencap'=>'CTDT','noidung'=>'Bản mô tả chương trình đào tạo đầy đủ thông tin, cập nhật, xác định rõ hình thức đào tạo từ xa, được công bố công khai và dễ dàng tiếp cận.'],
        	['tentieuchi'=>'Tiêu chí 2.2','tentieuchuan'=>'Tiêu chuẩn 2','tencap'=>'CTDT','noidung'=>'Đề cương chi tiết các môn học hoặc học phần đầy đủ thông tin, cập nhật, được công bố công khai và các bên liên quan dễ dàng tiếp cận.'],
        	['tentieuchi'=>'Tiêu chí 2.3','tentieuchuan'=>'Tiêu chuẩn 2','tencap'=>'CTDT','noidung'=>'Nội dung chương trình đào tạo được thiết kế dựa trên chuẩn đầu ra và chương trình đào tạo chính quy, cập nhật, có cấu trúc linh loạt, trình tự logic và gắn kết giữa các môn học hoặc học phần trong việc đạt được chuẩn đầu ra.'],
        	['tentieuchi'=>'Tiêu chí 3.1','tentieuchuan'=>'Tiêu chuẩn 3','tencap'=>'CTDT','noidung'=>'Các hoạt động dạy và học được thiết kế và triển khai thực hiện phù hợp với hình thức đào tạo từ xa.'],
        	['tentieuchi'=>'Tiêu chí 3.2','tentieuchuan'=>'Tiêu chuẩn 3','tencap'=>'CTDT','noidung'=>'Các hoạt động dạy và học được thiết kế phù hợp và triển khai thực hiện để đạt được chuẩn đầu ra.'],
        	['tentieuchi'=>'Tiêu chí 3.3','tentieuchuan'=>'Tiêu chuẩn 3','tencap'=>'CTDT','noidung'=>'Các hoạt động dạy và học được thiết kế và triển khai bảo đảm sự tương tác hiệu quả giữa người dạy và người học, giữa người học với nhau.'],
        	['tentieuchi'=>'Tiêu chí 3.4','tentieuchuan'=>'Tiêu chuẩn 3','tencap'=>'CTDT','noidung'=>'Các hoạt động dạy và học thúc đẩy việc rèn luyện các kỹ năng chuyên môn và kỹ năng mềm trong đó bao gồm cả kỹ năng tự học, tự nghiên cứu, nâng cao khả năng học tập suốt đời của người học.'],
        	['tentieuchi'=>'Tiêu chí 4.1','tentieuchuan'=>'Tiêu chuẩn 4','tencap'=>'CTDT','noidung'=>'Hoạt động kiểm tra, đánh giá kết quả học tập của người học (bao gồm cả xếp hạng tốt nghiệp, xét và công nhận tốt nghiệp, cấp phát văn bằng) được thiết kế và triển khai thực hiện phù hợp với hình thức đào tạo từ xa, đáp ứng đúng các quy định hiện hành.'],
        	['tentieuchi'=>'Tiêu chí 4.2','tentieuchuan'=>'Tiêu chuẩn 4','tencap'=>'CTDT','noidung'=>'Việc kiểm tra, đánh giá kết quả học tập của người học được thiết kế phù hợp với mức độ đạt được chuẩn đầu ra.'],
        	['tentieuchi'=>'Tiêu chí 4.3','tentieuchuan'=>'Tiêu chuẩn 4','tencap'=>'CTDT','noidung'=>'Quy định về kiểm tra, đánh giá kết quả học tập của người học (bao gồm thời gian, phương pháp, tiêu chí, trọng số, cơ chế phản hồi và các nội dung liên quan) rõ ràng và được thông báo công khai đến người học.'],
        	['tentieuchi'=>'Tiêu chí 4.4','tentieuchuan'=>'Tiêu chuẩn 4','tencap'=>'CTDT','noidung'=>'Phương pháp kiểm tra, đánh giá kết quả học tập đa dạng (trực tiếp, trực tuyến), bảo đảm độ giá trị, độ tin cậy; đánh giá chính xác, khách quan và công bằng.'],
        	['tentieuchi'=>'Tiêu chí 4.5','tentieuchuan'=>'Tiêu chuẩn 4','tencap'=>'CTDT','noidung'=>'Kết quả kiểm tra, đánh giá được phản hồi kịp thời để người học cải thiện việc học tập.'],
        	['tentieuchi'=>'Tiêu chí 4.6','tentieuchuan'=>'Tiêu chuẩn 4','tencap'=>'CTDT','noidung'=>'Ban hành và công khai quy trình giải quyết khiếu nại về kết quả kiểm tra, đánh giá để người học dễ dàng tiếp cận.'],
        	['tentieuchi'=>'Tiêu chí 4.7','tentieuchuan'=>'Tiêu chuẩn 4','tencap'=>'CTDT','noidung'=>'Có hệ thống giám sát phù hợp về sự tiến bộ trong học tập, kết quả học tập, khối lượng học tập của người học từ xa.'],
        	['tentieuchi'=>'Tiêu chí 5.1','tentieuchuan'=>'Tiêu chuẩn 5','tencap'=>'CTDT','noidung'=>'Có kế hoạch phát triển đội ngũ giảng viên, nghiên cứu viên, trợ giảng; việc tuyển dụng và phân công nhiệm vụ cho giảng viên, nghiên cứu viên, trợ giảng đáp ứng được các yêu cầu của chương trình đào tạo từ xa về các hoạt động đào tạo, nghiên cứu khoa học và phục vụ cộng đồng.'],
        	['tentieuchi'=>'Tiêu chí 5.2','tentieuchuan'=>'Tiêu chuẩn 5','tencap'=>'CTDT','noidung'=>'Yêu cầu về năng lực của giảng viên, nghiên cứu viên, trợ giảng thực hiện chương trình đào tạo từ xa được xác định và phổ biến công khai. Việc tuyển dụng và phân công nhiệm vụ cho giảng viên, nghiên cứu viên, trợ giảng đáp ứng được các yêu cầu của chương trình đào tạo từ xa và các quy định hiện hành.'],
        	['tentieuchi'=>'Tiêu chí 5.3','tentieuchuan'=>'Tiêu chuẩn 5','tencap'=>'CTDT','noidung'=>'Giảng viên, nghiên cứu viên, trợ giảng được tập huấn và định kỳ bồi dưỡng về phương pháp, kỹ năng làm việc, giảng dạy, nghiên cứu và ứng dụng công nghệ thông tin khi thực hiện chương trình đào tạo từ xa.'],
        	['tentieuchi'=>'Tiêu chí 5.4','tentieuchuan'=>'Tiêu chuẩn 5','tencap'=>'CTDT','noidung'=>'Đội ngũ giảng viên, nghiên cứu viên, trợ giảng được phân công công việc phù hợp chuyên môn được đào tạo để bảo đảm hiệu quả công việc.'],
        	['tentieuchi'=>'Tiêu chí 5.5','tentieuchuan'=>'Tiêu chuẩn 5','tencap'=>'CTDT','noidung'=>'Có cơ chế giám sát, đánh giá năng lực và khối lượng công việc của giảng viên, nghiên cứu viên, trợ giảng để cải tiến chất lượng các hoạt động đào tạo, nghiên cứu khoa học và phục vụ cộng đồng.'],
        	['tentieuchi'=>'Tiêu chí 5.6','tentieuchuan'=>'Tiêu chuẩn 5','tencap'=>'CTDT','noidung'=>'Nhu cầu về đào tạo, bồi dưỡng và phát triển chuyên môn của đội ngũ giảng viên, nghiên cứu viên, trợ giảng được xác định và có các hoạt động triển khai để đáp ứng nhu cầu đó.'],
        	['tentieuchi'=>'Tiêu chí 5.7','tentieuchuan'=>'Tiêu chuẩn 5','tencap'=>'CTDT','noidung'=>'Việc quản trị theo kết quả công việc của giảng viên, nghiên cứu viên, trợ giảng (bao gồm cả khen thưởng và công nhận) được triển khai để tạo động lực và hỗ trợ cho các hoạt động đào tạo, nghiên cứu khoa học và phục vụ cộng đồng.'],
        	['tentieuchi'=>'Tiêu chí 6.1','tentieuchuan'=>'Tiêu chuẩn 6','tencap'=>'CTDT','noidung'=>'Có kế hoạch phát triển đội ngũ nhân viên (làm việc tại thư viện, hệ thống công nghệ thông tin, xây dựng học liệu và các dịch vụ hỗ trợ khác) và thực hiện đáp ứng nhu cầu về đào tạo từ xa, nghiên cứu khoa học và phục vụ cộng đồng.'],
        	['tentieuchi'=>'Tiêu chí 6.2','tentieuchuan'=>'Tiêu chuẩn 6','tencap'=>'CTDT','noidung'=>'Các yêu cầu tuyển dụng, bổ nhiệm, điều chuyển và sử dụng đội ngũ nhân viên phù hợp với hình thức đào tạo từ xa và được xác định, phổ biến công khai.'],
        	['tentieuchi'=>'Tiêu chí 6.3','tentieuchuan'=>'Tiêu chuẩn 6','tencap'=>'CTDT','noidung'=>'Yêu cầu về năng lực và khối lượng công việc của nhân viên được xác định; có cơ chế giám sát, đánh giá và khuyến khích đội ngũ nhân viên.'],
        	['tentieuchi'=>'Tiêu chí 6.4','tentieuchuan'=>'Tiêu chuẩn 6','tencap'=>'CTDT','noidung'=>'Nhu cầu về đào tạo, bồi dưỡng và phát triển chuyên môn, nghiệp vụ của đội ngũ nhân viên được xác định và có các hoạt động được triển khai để đáp ứng nhu cầu đó.'],
        	['tentieuchi'=>'Tiêu chí 6.5','tentieuchuan'=>'Tiêu chuẩn 6','tencap'=>'CTDT','noidung'=>'Việc quản trị theo kết quả công việc của nhân viên (bao gồm cả khen thưởng và công nhận) được triển khai để tạo động lực và hỗ trợ cho các hoạt động đào tạo, nghiên cứu khoa học và phục vụ cộng đồng.'],
        	['tentieuchi'=>'Tiêu chí 7.1','tentieuchuan'=>'Tiêu chuẩn 7','tencap'=>'CTDT','noidung'=>'Chính sách tuyển sinh được xác định rõ ràng, có đối sánh với chương trình đào tạo chính quy cùng ngành, được công bố công khai và thường xuyên cập nhật.'],
        	['tentieuchi'=>'Tiêu chí 7.2','tentieuchuan'=>'Tiêu chuẩn 7','tencap'=>'CTDT','noidung'=>'Người học được trang bị phương pháp, kỹ năng học tập từ xa có hiệu quả.'],
        	['tentieuchi'=>'Tiêu chí 7.3','tentieuchuan'=>'Tiêu chuẩn 7','tencap'=>'CTDT','noidung'=>'Có các hoạt động tư vấn cho người học về phương pháp, kỹ năng học tập từ xa, kỹ năng nghề nghiệp và thái độ đối với nghề nghiệp; các dịch vụ hỗ trợ người học trong quá trình học tập và hoạt động ngoại khóa phù hợp với hình thức đào tạo từ xa.'],
        	['tentieuchi'=>'Tiêu chí 7.4','tentieuchuan'=>'Tiêu chuẩn 7','tencap'=>'CTDT','noidung'=>' Người học dễ dàng tiếp cận các hoạt động tư vấn và dịch vụ hỗ trợ giúp nâng cao chất lượng học tập.'],
        	['tentieuchi'=>'Tiêu chí 7.5','tentieuchuan'=>'Tiêu chuẩn 7','tencap'=>'CTDT','noidung'=>'Hệ thống thông tin tư vấn, hỗ trợ cho người học được cung cấp đầy đủ, rõ ràng trên Cổng thông tin đào tạo từ xa của cơ sở giáo dục; đội ngũ hỗ trợ bảo đảm sự tương tác, phản hồi thường xuyên, kịp thời cho người học.'],
        	['tentieuchi'=>'Tiêu chí 7.6','tentieuchuan'=>'Tiêu chuẩn 7','tencap'=>'CTDT','noidung'=>'Hệ thống lập kế hoạch, thực hiện, đánh giá và cải tiến môi trường, sức khỏe, sự an toàn và khả năng tiếp cận của người học có nhu cầu đặc biệt được thiết lập và vận hành.'],
        	['tentieuchi'=>'Tiêu chí 8.1','tentieuchuan'=>'Tiêu chuẩn 8','tencap'=>'CTDT','noidung'=>'Cơ sở hạ tầng công nghệ thông tin và hệ thống các phần mềm đáp ứng yêu cầu quản lý và đào tạo từ xa theo Quy chế đào tạo từ xa trình độ đại học do Bộ trưởng Bộ Giáo dục và Đào tạo ban hành.'],
        	['tentieuchi'=>'Tiêu chí 8.2','tentieuchuan'=>'Tiêu chuẩn 8','tencap'=>'CTDT','noidung'=>'Hệ thống công nghệ thông tin phục vụ đào tạo từ xa được đầu tư, phát triển, nâng cấp định kỳ.'],
        	['tentieuchi'=>'Tiêu chí 8.3','tentieuchuan'=>'Tiêu chuẩn 8','tencap'=>'CTDT','noidung'=>'Hệ thống phòng thu, trang thiết bị và hệ thống các phần mềm đáp ứng yêu cầu phát triển học liệu và hoạt động dạy và học.'],
        	['tentieuchi'=>'Tiêu chí 8.4','tentieuchuan'=>'Tiêu chuẩn 8','tencap'=>'CTDT','noidung'=>'Thư viện, bao gồm thư viện điện tử bảo đảm nguồn tài liệu đáp ứng yêu cầu chuyên môn của chương trình đào tạo và các nguồn tài nguyên khác đa dạng, phong phú, cập nhật, bảo đảm tính bản quyền, dễ dàng truy cập và đáp ứng được các yêu cầu theo Quy chế đào tạo từ xa trình độ đại học do Bộ trưởng Bộ Giáo dục và Đào tạo ban hành.'],
        	['tentieuchi'=>'Tiêu chí 8.5','tentieuchuan'=>'Tiêu chuẩn 8','tencap'=>'CTDT','noidung'=>'Học liệu, bao gồm học liệu điện tử phục vụ đào tạo từ xa được xây dựng phù hợp với chuẩn đầu ra và mục tiêu của chương trình đào tạo, đáp ứng được các yêu cầu theo Quy chế đào tạo từ xa trình độ đại học do Bộ trưởng Bộ Giáo dục và Đào tạo ban hành.'],
        	['tentieuchi'=>'Tiêu chí 8.6','tentieuchuan'=>'Tiêu chuẩn 8','tencap'=>'CTDT','noidung'=>'Học liệu, bao gồm học liệu điện tử phục vụ đào tạo từ xa được ban hành đầy đủ cho các môn học hoặc học phần trong chương trình đào tạo và được cung cấp tới người học.'],
        	['tentieuchi'=>'Tiêu chí 8.7','tentieuchuan'=>'Tiêu chuẩn 8','tencap'=>'CTDT','noidung'=>'Học liệu, bao gồm học liệu điện tử được lưu trữ đầy đủ, khoa học; được định kỳ bổ sung, cập nhật nhằm cải tiến chất lượng các hoạt động đào tạo từ xa.'],
        	['tentieuchi'=>'Tiêu chí 8.8','tentieuchuan'=>'Tiêu chuẩn 8','tencap'=>'CTDT','noidung'=>'Phòng thí nghiệm, thực hành và trang thiết bị phù hợp và được cập nhật để hỗ trợ các hoạt động đào tạo và nghiên cứu.'],
        	['tentieuchi'=>'Tiêu chí 9.1','tentieuchuan'=>'Tiêu chuẩn 9','tencap'=>'CTDT','noidung'=>'Phòng thí nghiệm, thực hành và trang thiết bị phù hợp và được cập nhật để hỗ trợ các hoạt động đào tạo và nghiên cứu.'],
        	['tentieuchi'=>'Tiêu chí 9.2','tentieuchuan'=>'Tiêu chuẩn 9','tencap'=>'CTDT','noidung'=>'Cơ sở giáo dục có quy định về tổ chức và quản lý triển khai thực hiện chương trình đào tạo từ xa hiệu quả và công bố công khai với các bên liên quan.'],
        	['tentieuchi'=>'Tiêu chí 9.3','tentieuchuan'=>'Tiêu chuẩn 9','tencap'=>'CTDT','noidung'=>' Việc quy hoạch, bổ nhiệm và bồi dưỡng cán bộ quản lý đáp ứng yêu cầu quản lý triển khai chương trình đào tạo từ xa.'],
        	['tentieuchi'=>'Tiêu chí 9.4','tentieuchuan'=>'Tiêu chuẩn 9','tencap'=>'CTDT','noidung'=>'Các tiêu chuẩn về môi trường, sức khỏe, an toàn được xác định và triển khai, có lưu ý đến nhu cầu đặc thù của người khuyết tật và phù hợp với hình thức đào tạo từ xa.'],
        	['tentieuchi'=>'Tiêu chí 9.5','tentieuchuan'=>'Tiêu chuẩn 9','tencap'=>'CTDT','noidung'=>'Bảo đảm nguồn tài chính và có kế hoạch đầu tư phát triển chương trình đào tạo từ xa và các điều kiện triển khai.'],
        	['tentieuchi'=>'Tiêu chí 10.1','tentieuchuan'=>'Tiêu chuẩn 10','tencap'=>'CTDT','noidung'=>'Thông tin phản hồi và nhu cầu của các bên liên quan về chương trình đào tạo từ xa được sử dụng làm căn cứ để xây dựng, đánh giá và phát triển chương trình dạy học.'],
        	['tentieuchi'=>'Tiêu chí 10.2','tentieuchuan'=>'Tiêu chuẩn 10','tencap'=>'CTDT','noidung'=>'Việc thiết kế và phát triển chương trình dạy học được xác lập, triển khai, đánh giá và cải tiến.'],
        	['tentieuchi'=>'Tiêu chí 10.3','tentieuchuan'=>'Tiêu chuẩn 10','tencap'=>'CTDT','noidung'=>'Có quy trình cụ thể định kỳ rà soát, đánh giá quá trình dạy và học, quy trình phân tích, đánh giá dựa trên dữ liệu về kết quả kiểm tra, đánh giá để bảo đảm người học đạt được chuẩn đầu ra và cải tiến chất lượng. Giám sát và lưu trữ được thông tin về sự tham gia, tiến bộ trong học tập, kết quả học tập, khối lượng học tập của người học từ xa.'],
        	['tentieuchi'=>'Tiêu chí 10.4','tentieuchuan'=>'Tiêu chuẩn 10','tencap'=>'CTDT','noidung'=>'Các kết quả nghiên cứu khoa học, học hỏi kinh nghiệm quốc tế được sử dụng để đánh giá và cải tiến việc dạy và học từ xa.'],
        	['tentieuchi'=>'Tiêu chí 10.5','tentieuchuan'=>'Tiêu chuẩn 10','tencap'=>'CTDT','noidung'=>'Chất lượng các dịch vụ hỗ trợ và tiện ích phục vụ đào tạo từ xa được đánh giá và cải tiến.'],
        	['tentieuchi'=>'Tiêu chí 11.1','tentieuchuan'=>'Tiêu chuẩn 11','tencap'=>'CTDT','noidung'=>'Tỉ lệ thôi học, tốt nghiệp được xác lập, giám sát và đối sánh để cải tiến chất lượng.'],
        	['tentieuchi'=>'Tiêu chí 11.2','tentieuchuan'=>'Tiêu chuẩn 11','tencap'=>'CTDT','noidung'=>' Thời gian tốt nghiệp trung bình được xác lập, giám sát và đối sánh để cải tiến chất lượng.'],
        	['tentieuchi'=>'Tiêu chí 11.3','tentieuchuan'=>'Tiêu chuẩn 11','tencap'=>'CTDT','noidung'=>'Mức độ hài lòng của các bên liên quan được xác lập, giám sát và đối sánh để cải tiến chất lượng.']
        ]);
    }
}
